gapi.loaded_0(function(_){var window=this;
_._F_toggles_initialize=function(a){("undefined"!==typeof globalThis?globalThis:"undefined"!==typeof self?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([0x100000, ]);
var ba,fa,ha,ma,na,va,wa,Ca;ba=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};fa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ha=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};_.la=ha(this);ma=function(a,b){if(b)a:{var c=_.la;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&fa(c,a,{configurable:!0,writable:!0,value:b})}};
ma("Symbol",function(a){if(a)return a;var b=function(f,h){this.L1=f;fa(this,"description",{configurable:!0,writable:!0,value:h})};b.prototype.toString=function(){return this.L1};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
ma("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=_.la[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&fa(d.prototype,a,{configurable:!0,writable:!0,value:function(){return na(ba(this))}})}return a});na=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.ra=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error("b`"+String(a));};va=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};wa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)va(d,e)&&(a[e]=d[e])}return a};ma("Object.assign",function(a){return a||wa});
_.ya="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
_.Ba=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=(0,_.ya)(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();
if("function"==typeof Object.setPrototypeOf)Ca=Object.setPrototypeOf;else{var Da;a:{var Ea={a:!0},Fa={};try{Fa.__proto__=Ea;Da=Fa.a;break a}catch(a){}Da=!1}Ca=Da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}_.Ga=Ca;ma("Reflect",function(a){return a?a:{}});ma("Reflect.construct",function(){return _.Ba});ma("Reflect.setPrototypeOf",function(a){return a?a:_.Ga?function(b,c){try{return(0,_.Ga)(b,c),!0}catch(d){return!1}}:null});
ma("Promise",function(a){function b(){this.Pf=null}function c(h){return h instanceof e?h:new e(function(k){k(h)})}if(a)return a;b.prototype.BP=function(h){if(null==this.Pf){this.Pf=[];var k=this;this.CP(function(){k.d8()})}this.Pf.push(h)};var d=_.la.setTimeout;b.prototype.CP=function(h){d(h,0)};b.prototype.d8=function(){for(;this.Pf&&this.Pf.length;){var h=this.Pf;this.Pf=[];for(var k=0;k<h.length;++k){var l=h[k];h[k]=null;try{l()}catch(m){this.wq(m)}}}this.Pf=null};b.prototype.wq=function(h){this.CP(function(){throw h;
})};var e=function(h){this.Ga=0;this.Gf=void 0;this.cs=[];this.JV=!1;var k=this.BF();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.BF=function(){function h(m){return function(n){l||(l=!0,m.call(k,n))}}var k=this,l=!1;return{resolve:h(this.Dea),reject:h(this.qK)}};e.prototype.Dea=function(h){if(h===this)this.qK(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof e)this.pga(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;
default:k=!1}k?this.Cea(h):this.MS(h)}};e.prototype.Cea=function(h){var k=void 0;try{k=h.then}catch(l){this.qK(l);return}"function"==typeof k?this.qga(k,h):this.MS(h)};e.prototype.qK=function(h){this.A_(2,h)};e.prototype.MS=function(h){this.A_(1,h)};e.prototype.A_=function(h,k){if(0!=this.Ga)throw Error("c`"+h+"`"+k+"`"+this.Ga);this.Ga=h;this.Gf=k;2===this.Ga&&this.Sea();this.e8()};e.prototype.Sea=function(){var h=this;d(function(){if(h.Kca()){var k=_.la.console;"undefined"!==typeof k&&k.error(h.Gf)}},
1)};e.prototype.Kca=function(){if(this.JV)return!1;var h=_.la.CustomEvent,k=_.la.Event,l=_.la.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof k?h=new k("unhandledrejection",{cancelable:!0}):(h=_.la.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.Gf;return l(h)};e.prototype.e8=function(){if(null!=this.cs){for(var h=0;h<this.cs.length;++h)f.BP(this.cs[h]);
this.cs=null}};var f=new b;e.prototype.pga=function(h){var k=this.BF();h.Ay(k.resolve,k.reject)};e.prototype.qga=function(h,k){var l=this.BF();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};e.prototype.then=function(h,k){function l(q,u){return"function"==typeof q?function(v){try{m(q(v))}catch(t){n(t)}}:u}var m,n,p=new e(function(q,u){m=q;n=u});this.Ay(l(h,m),l(k,n));return p};e.prototype.catch=function(h){return this.then(void 0,h)};e.prototype.Ay=function(h,k){function l(){switch(m.Ga){case 1:h(m.Gf);
break;case 2:k(m.Gf);break;default:throw Error("d`"+m.Ga);}}var m=this;null==this.cs?f.BP(l):this.cs.push(l);this.JV=!0};e.resolve=c;e.reject=function(h){return new e(function(k,l){l(h)})};e.race=function(h){return new e(function(k,l){for(var m=_.ra(h),n=m.next();!n.done;n=m.next())c(n.value).Ay(k,l)})};e.all=function(h){var k=_.ra(h),l=k.next();return l.done?c([]):new e(function(m,n){function p(v){return function(t){q[v]=t;u--;0==u&&m(q)}}var q=[],u=0;do q.push(void 0),u++,c(l.value).Ay(p(q.length-
1),n),l=k.next();while(!l.done)})};return e});var Ha=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
ma("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Ha(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});
ma("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!va(l,f)){var m=new b;fa(l,f,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,k=function(l){this.Ha=(h+=Math.random()+1).toString();if(l){l=_.ra(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("e");d(l);if(!va(l,f))throw Error("f`"+l);l[f][this.Ha]=m;return this};k.prototype.get=function(l){return c(l)&&va(l,f)?l[f][this.Ha]:void 0};k.prototype.has=function(l){return c(l)&&va(l,f)&&va(l[f],this.Ha)};k.prototype.delete=
function(l){return c(l)&&va(l,f)&&va(l[f],this.Ha)?delete l[f][this.Ha]:!1};return k});
ma("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.ra([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(k){this[0]={};this[1]=
f();this.size=0;if(k){k=_.ra(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this[0][m.id]=[]);m.tf?m.tf.value=l:(m.tf={next:this[1],nl:this[1].nl,head:this[1],key:k,value:l},m.list.push(m.tf),this[1].nl.next=m.tf,this[1].nl=m.tf,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.tf&&k.list?(k.list.splice(k.index,1),k.list.length||delete this[0][k.id],k.tf.nl.next=k.tf.next,k.tf.next.nl=
k.tf.nl,k.tf.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].nl=f();this.size=0};c.prototype.has=function(k){return!!d(this,k).tf};c.prototype.get=function(k){return(k=d(this,k).tf)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),
n;!(n=m.next()).done;)n=n.value,k.call(l,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++h,b.set(l,m)):m="p_"+l;var n=k[0][m];if(n&&va(k[0],m))for(k=0;k<n.length;k++){var p=n[k];if(l!==l&&p.key!==p.key||l===p.key)return{id:m,list:n,index:k,tf:p}}return{id:m,list:n,index:-1,tf:void 0}},e=function(k,l){var m=k[1];return na(function(){if(m){for(;m.head!=k[1];)m=m.nl;for(;m.next!=m.head;)return m=
m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},f=function(){var k={};return k.nl=k.next=k.head=k},h=0;return c});ma("Object.setPrototypeOf",function(a){return a||_.Ga});ma("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Ha(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});
var La=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};ma("Array.prototype.keys",function(a){return a?a:function(){return La(this,function(b){return b})}});
ma("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.ra([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(h){return!1}}())return a;var b=function(c){this.Aa=new Map;if(c){c=
_.ra(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.Aa.size};b.prototype.add=function(c){c=0===c?0:c;this.Aa.set(c,c);this.size=this.Aa.size;return this};b.prototype.delete=function(c){c=this.Aa.delete(c);this.size=this.Aa.size;return c};b.prototype.clear=function(){this.Aa.clear();this.size=0};b.prototype.has=function(c){return this.Aa.has(c)};b.prototype.entries=function(){return this.Aa.entries()};b.prototype.values=function(){return this.Aa.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.Aa.forEach(function(f){return c.call(d,f,f,e)})};return b});ma("Array.prototype.entries",function(a){return a?a:function(){return La(this,function(b,c){return[b,c]})}});var Ma=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{PU:e,VD:f}}return{PU:-1,VD:void 0}};
ma("Array.prototype.find",function(a){return a?a:function(b,c){return Ma(this,b,c).VD}});ma("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});ma("Array.prototype.values",function(a){return a?a:function(){return La(this,function(b,c){return c})}});
ma("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});ma("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)va(b,d)&&c.push([d,b[d]]);return c}});
ma("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)va(b,d)&&c.push(b[d]);return c}});ma("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ma("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
ma("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Ha(this,b,"includes").indexOf(b,c||0)}});ma("Array.prototype.flat",function(a){return a?a:function(b){b=void 0===b?1:b;var c=[];Array.prototype.forEach.call(this,function(d){Array.isArray(d)&&0<b?(d=Array.prototype.flat.call(d,b-1),c.push.apply(c,d)):c.push(d)});return c}});ma("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
ma("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});ma("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});ma("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ma("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});
ma("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});ma("Array.prototype.findIndex",function(a){return a?a:function(b,c){return Ma(this,b,c).PU}});
ma("String.fromCodePoint",function(a){return a?a:function(b){for(var c="",d=0;d<arguments.length;d++){var e=Number(arguments[d]);if(0>e||1114111<e||e!==Math.floor(e))throw new RangeError("invalid_code_point "+e);65535>=e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(e>>>10&1023|55296),c+=String.fromCharCode(e&1023|56320))}return c}});
ma("String.prototype.codePointAt",function(a){return a?a:function(b){var c=Ha(this,null,"codePointAt"),d=c.length;b=Number(b)||0;if(0<=b&&b<d){b|=0;var e=c.charCodeAt(b);if(55296>e||56319<e||b+1===d)return e;b=c.charCodeAt(b+1);return 56320>b||57343<b?e:1024*(e-55296)+b+9216}}});ma("globalThis",function(a){return a||_.la});ma("Math.imul",function(a){return a?a:function(b,c){b=Number(b);c=Number(c);var d=b&65535,e=c&65535;return d*e+((b>>>16&65535)*e+d*(c>>>16&65535)<<16>>>0)|0}});
ma("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});_.Pa={};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Ta=_.Ta||{};_.Va=this||self;_.Wa=_.Va._F_toggles||[];_.Ya="closure_uid_"+(1E9*Math.random()>>>0);_.$a=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.r=function(a,b){a=a.split(".");var c=_.Va;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};
_.ab=function(a,b){function c(){}c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.It=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};_.db=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
blogger:{url:":socialhost:/:session_prefix:_/widget/render/blogger?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},appfinder:{url:"https://workspace.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{rpc:"/rpc",root:"https://content.googleapis.com",
"root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});
var jb,kb;_.ib=function(a){return function(){return _.gb[a].apply(this,arguments)}};_.gb=[];jb=function(a,b,c){return a.call.apply(a.bind,arguments)};kb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};
_.z=function(a,b,c){_.z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?jb:kb;return _.z.apply(null,arguments)};
/*

 SPDX-License-Identifier: Apache-2.0
*/
var Db,Jb,Yb,nc,zc,Bc,Fc,Ic,Jc,Kc,Pc,Qc,Tc;_.lb=function(a,b){return _.gb[a]=b};_.ob=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ob);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b);this.UY=!0};_.qb=function(a,b){return 0<=(0,_.pb)(a,b)};_.rb=function(a,b){b=(0,_.pb)(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};_.sb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.tb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.ub=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.vb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.xb=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};_.Bb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ab.length;f++)c=Ab[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Cb=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return _.Cb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};Db=function(a){return{valueOf:a}.valueOf()};_.Hb=function(a){if(a instanceof _.Gb)return a.xY;throw Error("m");};Jb=function(a){return new Ib(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})};
_.Mb=function(a){var b=void 0===b?Kb:b;a:if(b=void 0===b?Kb:b,!(a instanceof _.Gb)){for(var c=0;c<b.length;++c){var d=b[c];if(d instanceof Ib&&d.Jj(a)){a=new _.Gb(a);break a}}a=void 0}return a||_.Lb};_.Ob=function(a){if(Nb.test(a))return a};_.Pb=function(a){return a instanceof _.Gb?_.Hb(a):_.Ob(a)};
_.Tb=function(a,b){b=void 0===b?{}:b;if(a instanceof _.Qb)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");b.Ura&&(a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;"));b.Qda&&(a=a.replace(/(\r\n|\n|\r)/g,"<br>"));b.Vra&&(a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>'));return _.Rb(a)};_.Ub=function(){var a=_.Va.navigator;return a&&(a=a.userAgent)?a:""};
Yb=function(a){return _.Vb?_.Wb?_.Wb.brands.some(function(b){return(b=b.brand)&&_.Xb(b,a)}):!1:!1};_.Zb=function(a){return _.Xb(_.Ub(),a)};_.$b=function(a){for(var b=RegExp("([A-Z][\\w ]+)/([^\\s]+)\\s*(?:\\((.*?)\\))?","g"),c=[],d;d=b.exec(a);)c.push([d[1],d[2],d[3]||void 0]);return c};_.ac=function(){return _.Vb?!!_.Wb&&0<_.Wb.brands.length:!1};_.bc=function(){return _.ac()?!1:_.Zb("Opera")};_.cc=function(){return _.ac()?!1:_.Zb("Trident")||_.Zb("MSIE")};_.dc=function(){return _.ac()?!1:_.Zb("Edge")};
_.ec=function(){return _.ac()?Yb("Microsoft Edge"):_.Zb("Edg/")};_.fc=function(){return _.ac()?Yb("Opera"):_.Zb("OPR")};_.gc=function(){return _.Zb("Firefox")||_.Zb("FxiOS")};_.jc=function(){return _.Zb("Safari")&&!(_.hc()||(_.ac()?0:_.Zb("Coast"))||_.bc()||_.dc()||_.ec()||_.fc()||_.gc()||_.Zb("Silk")||_.Zb("Android"))};_.hc=function(){return _.ac()?Yb("Chromium"):(_.Zb("Chrome")||_.Zb("CriOS"))&&!_.dc()||_.Zb("Silk")};_.kc=function(){return _.Zb("Android")&&!(_.hc()||_.gc()||_.bc()||_.Zb("Silk"))};
_.lc=function(a){var b={};a.forEach(function(c){b[c[0]]=c[1]});return function(c){return b[c.find(function(d){return d in b})]||""}};_.mc=function(a){var b=/rv: *([\d\.]*)/.exec(a);if(b&&b[1])return b[1];b="";var c=/MSIE +([\d\.]+)/.exec(a);if(c&&c[1])if(a=/Trident\/(\d.\d)/.exec(a),"7.0"==c[1])if(a&&a[1])switch(a[1]){case "4.0":b="8.0";break;case "5.0":b="9.0";break;case "6.0":b="10.0";break;case "7.0":b="11.0"}else b="7.0";else b=c[1];return b};
nc=function(){return _.Vb?!!_.Wb&&!!_.Wb.platform:!1};_.oc=function(){return nc()?"Android"===_.Wb.platform:_.Zb("Android")};_.pc=function(){return _.Zb("iPhone")&&!_.Zb("iPod")&&!_.Zb("iPad")};_.qc=function(){return _.pc()||_.Zb("iPad")||_.Zb("iPod")};_.rc=function(){return nc()?"macOS"===_.Wb.platform:_.Zb("Macintosh")};_.sc=function(){return nc()?"Windows"===_.Wb.platform:_.Zb("Windows")};_.tc=function(){return nc()?"Chrome OS"===_.Wb.platform:_.Zb("CrOS")};
_.vc=function(a,b){if(1===a.nodeType){var c=a.tagName;if("SCRIPT"===c||"STYLE"===c)throw Error("m");}a.innerHTML=_.uc(b)};_.wc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.xc=function(a){if(!(a instanceof Array)){a=_.ra(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a};
_.A=function(a,b){a.prototype=(0,_.ya)(b.prototype);a.prototype.constructor=a;if(_.Ga)(0,_.Ga)(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.N=b.prototype};_.yc=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};_.Ac=function(a,b){a=a.split(".");b=b||_.Va;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};
Bc=function(a){var b=_.Ac("WIZ_global_data.oxN3nb");a=b&&b[a];return null!=a?a:!1};_.Cc=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};_.Ec=function(a){var b=_.Cc(a);return"array"==b||"object"==b&&"number"==typeof a.length};Fc=0;_.Gc=function(a){return Object.prototype.hasOwnProperty.call(a,_.Ya)&&a[_.Ya]||(a[_.Ya]=++Fc)};_.Hc=function(){return Date.now()};Ic=function(a){return a};_.ab(_.ob,Error);_.ob.prototype.name="CustomError";Jc={};Kc={};
_.Mc=function(a,b){this.l0=a===Jc&&b||"";this.B5=Kc};_.Mc.prototype.toString=function(){return this.l0};_.Nc=function(a){return a instanceof _.Mc&&a.constructor===_.Mc&&a.B5===Kc?a.l0:"type_error:Const"};_.Oc=function(a){return new _.Mc(Jc,a)};Qc=function(){if(void 0===Pc){var a=null,b=_.Va.trustedTypes;if(b&&b.createPolicy)try{a=b.createPolicy("goog#html",{createHTML:Ic,createScript:Ic,createScriptURL:Ic})}catch(c){_.Va.console&&_.Va.console.error(c.message)}Pc=a}return Pc};
_.Rc=function(a){this.vY=a};_.Rc.prototype.toString=function(){return this.vY+""};_.Sc=function(a){if(a instanceof _.Rc&&a.constructor===_.Rc)return a.vY;_.Cc(a);return"type_error:TrustedResourceUrl"};Tc={};_.Uc=function(a){var b=Qc();a=b?b.createScriptURL(a):a;return new _.Rc(a,Tc)};_.Vc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
_.pb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.Wc=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.Xc=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Yc=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};_.Zc=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f="string"===typeof a?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.$c=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;(0,_.Xc)(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d};_.ad=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
_.bd=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};var Ab="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var hd,id,jd,kd,ld,md,fd,od;_.cd=function(a,b){return 0==a.lastIndexOf(b,0)};_.dd=function(a){return/^[\s\xa0]*$/.test(a)};_.ed=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.nd=function(a){if(!fd.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(hd,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(id,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(jd,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(kd,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ld,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(md,"&#0;"));return a};hd=/&/g;id=/</g;jd=/>/g;kd=/"/g;ld=/'/g;md=/\x00/g;fd=/[\x00&<>"']/;_.Xb=function(a,b){return-1!=a.indexOf(b)};
_.pd=function(a,b){var c=0;a=(0,_.ed)(String(a)).split(".");b=(0,_.ed)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=od(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||od(0==f[2].length,0==h[2].length)||od(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c};
od=function(a,b){return a<b?-1:a>b?1:0};_.Gb=function(a){this.xY=a};_.Gb.prototype.toString=function(){return this.xY};_.Lb=new _.Gb("about:invalid#zClosurez");var Ib,Kb,Nb;Ib=function(a){this.Jj=a};Kb=[Jb("data"),Jb("http"),Jb("https"),Jb("mailto"),Jb("ftp"),new Ib(function(a){return/^[^:]*([/?#]|$)/.test(a)})];_.qd=Db(function(){return"function"===typeof URL});Nb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;_.rd={};_.sd=function(a){this.uY=a};_.sd.prototype.toString=function(){return this.uY.toString()};_.td=new _.sd("",_.rd);_.ud=RegExp("^[-+,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$");_.vd=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g");_.wd=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|radial-gradient|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|steps|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g");var zd;_.xd={};_.yd=function(a){this.tY=a};_.yd.prototype.toString=function(){return this.tY.toString()};_.Ad=function(a){a=_.Nc(a);return 0===a.length?zd:new _.yd(a,_.xd)};zd=new _.yd("",_.xd);var Bd;Bd={};_.Qb=function(a){this.sY=a};_.Qb.prototype.toString=function(){return this.sY.toString()};_.uc=function(a){if(a instanceof _.Qb&&a.constructor===_.Qb)return a.sY;_.Cc(a);return"type_error:SafeHtml"};_.Cd=function(a){return a instanceof _.Qb?a:_.Rb(_.nd(String(a)))};_.Rb=function(a){var b=Qc();a=b?b.createHTML(a):a;return new _.Qb(a,Bd)};_.Dd=new _.Qb(_.Va.trustedTypes&&_.Va.trustedTypes.emptyHTML||"",Bd);var Fd=function(a,b,c,d){var e=new Map(Ed);this.p6=a;this.uR=e;this.q6=b;this.j$=c;this.OT=d};var Gd="ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" "),
Ed=[["A",new Map([["href",{Cd:2}]])],["AREA",new Map([["href",{Cd:2}]])],["LINK",new Map([["href",{Cd:2,conditions:new Map([["rel",new Set("alternate author bookmark canonical cite help icon license next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" "))]])}]])],["SOURCE",new Map([["src",{Cd:1}],["srcset",{Cd:1}]])],["IMG",new Map([["src",{Cd:1}],["srcset",{Cd:1}]])],["VIDEO",new Map([["src",{Cd:1}]])],["AUDIO",new Map([["src",{Cd:1}]])]],Hd="title aria-atomic aria-autocomplete aria-busy aria-checked aria-current aria-disabled aria-dropeffect aria-expanded aria-haspopup aria-hidden aria-invalid aria-label aria-level aria-live aria-multiline aria-multiselectable aria-orientation aria-posinset aria-pressed aria-readonly aria-relevant aria-required aria-selected aria-setsize aria-sort aria-valuemax aria-valuemin aria-valuenow aria-valuetext alt align autocapitalize autocomplete autocorrect autofocus autoplay bgcolor border cellpadding cellspacing checked color cols colspan controls datetime disabled download draggable enctype face formenctype frameborder height hreflang hidden ismap label lang loop max maxlength media minlength min multiple muted nonce open placeholder preload rel required reversed role rows rowspan selected shape size sizes slot span spellcheck start step summary translate type valign value width wrap itemscope itemtype itemid itemprop itemref".split(" "),
Id=[["dir",{Cd:3,conditions:Db(function(){return new Map([["dir",new Set(["auto","ltr","rtl"])]])})}],["async",{Cd:3,conditions:Db(function(){return new Map([["async",new Set(["async"])]])})}],["cite",{Cd:2}],["loading",{Cd:3,conditions:Db(function(){return new Map([["loading",new Set(["eager","lazy"])]])})}],["poster",{Cd:2}],["target",{Cd:3,conditions:Db(function(){return new Map([["target",new Set(["_self","_blank"])]])})}]],Jd=new Fd(new Set(Gd),new Set(Hd),new Map(Id)),Kd=new Fd(new Set(Gd.concat(["BUTTON",
"INPUT"])),new Set(Db(function(){return Hd.concat(["class","id","name"])})),new Map(Db(function(){return Id.concat([["style",{Cd:1}]])}))),Ld=new Fd(new Set(Db(function(){return Gd.concat("STYLE TITLE INPUT TEXTAREA BUTTON LABEL".split(" "))})),new Set(Db(function(){return Hd.concat(["class","id","tabindex","contenteditable","name"])})),new Map(Db(function(){return Id.concat([["style",{Cd:1}]])})),new Set(["data-","aria-"]));var Md;Md=function(a){this.oZ=a};_.Nd=Db(function(){return new Md(Jd)});_.Od=Db(function(){return new Md(Kd)});_.Pd=Db(function(){return new Md(Ld)});var Qd=!!(_.Wa[0]&512),Rd=!!(_.Wa[0]&1024),Sd=!!(_.Wa[0]&8);_.Vb=Qd?Rd:Bc(610401301);_.Td=Qd?Sd:Bc(188588736);var Ud;Ud=_.Va.navigator;_.Wb=Ud?Ud.userAgentData||null:null;_.Vd=function(a){_.Vd[" "](a);return a};_.Vd[" "]=function(){};_.Wd=function(a,b){try{return _.Vd(a[b]),!0}catch(c){}return!1};var me,ne,se;_.Xd=_.bc();_.Zd=_.cc();_.$d=_.Zb("Edge");_.ae=_.$d||_.Zd;_.be=_.Zb("Gecko")&&!(_.Xb(_.Ub().toLowerCase(),"webkit")&&!_.Zb("Edge"))&&!(_.Zb("Trident")||_.Zb("MSIE"))&&!_.Zb("Edge");_.ce=_.Xb(_.Ub().toLowerCase(),"webkit")&&!_.Zb("Edge");_.de=_.ce&&_.Zb("Mobile");_.ee=_.rc();_.fe=_.sc();_.ge=(nc()?"Linux"===_.Wb.platform:_.Zb("Linux"))||_.tc();_.he=_.oc();_.ie=_.pc();_.je=_.Zb("iPad");_.ke=_.Zb("iPod");_.le=_.qc();me=function(){var a=_.Va.document;return a?a.documentMode:void 0};
a:{var oe="",pe=function(){var a=_.Ub();if(_.be)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.$d)return/Edge\/([\d\.]+)/.exec(a);if(_.Zd)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.ce)return/WebKit\/(\S+)/.exec(a);if(_.Xd)return/(?:Version)[ \/]?(\S+)/.exec(a)}();pe&&(oe=pe?pe[1]:"");if(_.Zd){var qe=me();if(null!=qe&&qe>parseFloat(oe)){ne=String(qe);break a}}ne=oe}_.re=ne;if(_.Va.document&&_.Zd){var te=me();se=te?te:parseInt(_.re,10)||void 0}else se=void 0;_.ue=se;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var ve,xe;ve=_.Vc(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.uc(_.Dd);return!b.parentElement});_.we=function(a,b){if(ve())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=_.uc(b)};xe=/^[\w+/_-]+[=]{0,2}$/;_.ye=function(a,b){b=(b||_.Va).document;return b.querySelector?(a=b.querySelector(a))&&(a=a.nonce||a.getAttribute("nonce"))&&xe.test(a)?a:"":""};_.ze=function(a,b){this.width=a;this.height=b};_.Ae=function(a,b){return a==b?!0:a&&b?a.width==b.width&&a.height==b.height:!1};_.g=_.ze.prototype;_.g.clone=function(){return new _.ze(this.width,this.height)};_.g.jy=function(){return this.width*this.height};_.g.aspectRatio=function(){return this.width/this.height};_.g.isEmpty=function(){return!this.jy()};_.g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
_.g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.g.scale=function(a,b){this.width*=a;this.height*="number"===typeof b?b:a;return this};_.De=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Ee=2147483648*Math.random()|0;var Ke,Re,Qe;_.He=function(a){return a?new _.Fe(_.Ge(a)):zc||(zc=new _.Fe)};_.Ie=function(a,b){return"string"===typeof b?a.getElementById(b):b};
_.Je=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.qb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Le=function(a,b){_.tb(b,function(c,d){"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Ke.hasOwnProperty(d)?a.setAttribute(Ke[d],c):_.cd(d,"aria-")||_.cd(d,"data-")?a.setAttribute(d,c):a[d]=c})};Ke={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};_.Ne=function(a){return _.Me(a||window)};
_.Me=function(a){a=a.document;a=_.Oe(a)?a.documentElement:a.body;return new _.ze(a.clientWidth,a.clientHeight)};_.Pe=function(a){return a?a.parentWindow||a.defaultView:window};_.Se=function(a,b){var c=b[1],d=Qe(a,String(b[0]));c&&("string"===typeof c?d.className=c:Array.isArray(c)?d.className=c.join(" "):_.Le(d,c));2<b.length&&Re(a,d,b,2);return d};
Re=function(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!_.Ec(f)||_.wc(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(_.wc(f)){var h="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){h="function"==typeof f.item;break a}}h=!1}_.Xc(h?_.sb(f):f,e)}}};_.Te=function(a){return Qe(document,a)};
Qe=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.Oe=function(a){return"CSS1Compat"==a.compatMode};_.Ue=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.Ve=function(a,b){Re(_.Ge(a),a,arguments,1)};_.Xe=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Ye=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.Ze=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.$e=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};_.af=function(a){return _.wc(a)&&1==a.nodeType};
_.bf=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Ge=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.cf=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.Xe(a),a.appendChild(_.Ge(a).createTextNode(String(b)))};_.Fe=function(a){this.Rb=a||_.Va.document||document};_.g=_.Fe.prototype;_.g.Ka=_.He;_.g.sL=_.ib(0);_.g.Bb=function(){return this.Rb};_.g.O=_.ib(1);_.g.getElementsByTagName=function(a,b){return(b||this.Rb).getElementsByTagName(String(a))};
_.g.xH=_.ib(2);_.g.wa=function(a,b,c){return _.Se(this.Rb,arguments)};_.g.createElement=function(a){return Qe(this.Rb,a)};_.g.createTextNode=function(a){return this.Rb.createTextNode(String(a))};_.g.getWindow=function(){var a=this.Rb;return a.parentWindow||a.defaultView};_.g.appendChild=function(a,b){a.appendChild(b)};_.g.append=_.Ve;_.g.canHaveChildren=_.Ue;_.g.De=_.Xe;_.g.lV=_.Ye;_.g.removeNode=_.Ze;_.g.GG=_.$e;_.g.isElement=_.af;_.g.contains=_.bf;_.g.aH=_.Ge;_.g.Hj=_.ib(3);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.df=function(a){return null===a?"null":void 0===a?"undefined":a};_.ef=window;_.ff=document;_.gf=_.ef.location;_.hf=/\[native code\]/;_.jf=function(a,b,c){return a[b]=a[b]||c};_.kf=function(){var a;if((a=Object.create)&&_.hf.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.lf=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.mf=function(a,b){a=a||{};for(var c in a)_.lf(a,c)&&(b[c]=a[c])};_.nf=_.jf(_.ef,"gapi",{});_.of=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=decodeURIComponent(a[2])}catch(e){}return c};_.pf=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);_.qf=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");
_.rf=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");_.tf=function(a,b,c){_.sf(a,b,c,"add","at")};_.sf=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.uf={};_.uf=_.jf(_.ef,"___jsl",_.kf());_.jf(_.uf,"I",0);_.jf(_.uf,"hel",10);var vf,wf,yf,zf,Bf,Af,Cf,Df;vf=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};wf=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};yf=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
zf=function(a,b,c){if(b&&"object"===typeof b)for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&"___goc"===d&&"undefined"===typeof b[d]||(a[d]&&b[d]&&"object"===typeof a[d]&&"object"===typeof b[d]&&!yf(a[d])&&!yf(b[d])?zf(a[d],b[d]):b[d]&&"object"===typeof b[d]?(a[d]=yf(b[d])?[]:{},zf(a[d],b[d])):a[d]=b[d])};
Bf=function(a,b){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c=a;try{var d=window.JSON.parse(a)}catch(f){}if("object"===typeof d)return d;try{d=window.JSON.parse("{"+a+"}")}catch(f){}if("object"===typeof d)return d;a=a.replace(RegExp("([^\"',{}\\s]+?)\\s*:\\s*(.*?)[,}\\s]","g"),function(f,h,k){k=k.startsWith('"')?"%DOUBLE_QUOTE%"+k.substring(1):k;k=k.endsWith('"')?k.slice(0,-1)+"%DOUBLE_QUOTE%":k;return"%DOUBLE_QUOTE%"+h+"%DOUBLE_QUOTE%:"+k});a=a.replace(/\\'/g,
"%SINGLE_QUOTE%");a=a.replace(/"/g,'\\"');a=a.replace(/'/g,'"');a=a.replace(/%SINGLE_QUOTE%/g,"'");a=a.replace(/%DOUBLE_QUOTE%/g,'"');try{d=window.JSON.parse(a)}catch(f){}if("object"===typeof d)return d;try{d=window.JSON.parse("{"+a+"}")}catch(f){}if("object"===typeof d)return d;a=document.getElementsByTagName("script")||[];var e;0<a.length&&(e=a[0].nonce||a[0].getAttribute("nonce"));if(e&&e!==b)return{};d=Af(c);return"object"===typeof d?d:{}}};
Af=function(a){try{var b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return b};Cf=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(c=a.pop());zf(c,b);a.push(c)};
Df=function(a){wf(!0);var b=window.___gcfg,c=vf("cu"),d=window.___gu;b&&b!==d&&(Cf(c,b),window.___gu=b);b=vf("cu");var e=document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,vf("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),(f=d[e])?(h=f.nodeType,f=3==h||
4==h?f.nodeValue:f.textContent||""):f=void 0,h=d[e].nonce||d[e].getAttribute("nonce"),(f=Bf(f,h))&&b.push(f));a&&Cf(c,a);d=vf("cd");a=0;for(b=d.length;a<b;++a)zf(wf(),d[a],!0);d=vf("ci");a=0;for(b=d.length;a<b;++a)zf(wf(),d[a],!0);a=0;for(b=c.length;a<b;++a)zf(wf(),c[a],!0)};_.Ef=function(a,b){var c=wf();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b};
_.Ff=function(a,b){var c;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var h={};d=d[a[e]]=h}d[a[e]]=b}else c=a;Df(c)};var Gf=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.jf(_.uf,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};Gf&&Gf();Df();_.r("gapi.config.get",_.Ef);_.r("gapi.config.update",_.Ff);
var Hf,If,Jf,Kf,Lf,Mf,Of,Sf,Tf,Uf,Vf,Pf,Qf;Hf=function(a,b){var c=b.createRange();c.selectNode(b.body);a=_.Rb(a);return c.createContextualFragment(_.uc(a))};If=function(a){a=a.nodeName;return"string"===typeof a?a:"FORM"};Jf=function(a){a=a.nodeType;return 1===a||"number"!==typeof a};Kf=function(a,b,c){a.setAttribute(b,c)};Lf=function(a,b){var c=new XMLHttpRequest;c.open("POST",a);c.setRequestHeader("Content-Type","application/json");c.send(b)};
Mf=function(a,b){("undefined"!==typeof window&&window.navigator&&void 0!==window.navigator.sendBeacon?navigator.sendBeacon.bind(navigator):Lf)("https://csp.withgoogle.com/csp/lcreport/"+a.vK,JSON.stringify({host:window.location.hostname,type:b,additionalData:void 0}))};Of=function(a,b){try{_.Nf(_.Pd,a)}catch(c){return Mf(b,"H_SLSANITIZE"),!0}try{_.Nf(_.Od,a)}catch(c){return Mf(b,"H_RSANITIZE"),!0}try{_.Nf(_.Nd,a)}catch(c){return Mf(b,"H_SANITIZE"),!0}return!1};
_.Rf=function(a,b){a=_.df(a);var c;if(c=b){var d,e;c=Math.random()<(null!=(e=null!=(d=b.osa)?d:Pf[b.vK[0]])?e:0)}if(c&&!1!==window.SAFEVALUES_REPORTING&&"DocumentFragment"in window){var f,h;Math.random()<(null!=(h=null!=(f=b.ira)?f:Qf[b.vK[0]])?h:0)&&Mf(b,"HEARTBEAT");Of(a,b)||_.Tb(a).toString()!==a&&Mf(b,"H_ESCAPE")}return _.Rb(a)};Sf=["data:","http:","https:","mailto:","ftp:"];
Tf=function(a,b,c){c=a.uR.get(c);return(null==c?0:c.has(b))?c.get(b):a.q6.has(b)?{Cd:1}:(c=a.j$.get(b))?c:a.OT&&[].concat(_.xc(a.OT)).some(function(d){return 0===b.indexOf(d)})?{Cd:1}:{Cd:0}};
Uf=function(a,b,c){var d=If(b);c=c.createElement(d);b=b.attributes;for(var e=_.ra(b),f=e.next();!f.done;f=e.next()){var h=f.value;f=h.name;h=h.value;var k=Tf(a.oZ,f,d),l;a:{if(l=k.conditions){l=_.ra(l);for(var m=l.next();!m.done;m=l.next()){var n=_.ra(m.value);m=n.next().value;n=n.next().value;var p=void 0;if((m=null==(p=b.getNamedItem(m))?void 0:p.value)&&!n.has(m)){l=!1;break a}}}l=!0}if(l)switch(k.Cd){case 1:Kf(c,f,h);break;case 2:a:if(k=void 0,_.qd){try{k=new URL(h)}catch(q){k="https:";break a}k=
k.protocol}else b:{k=document.createElement("a");try{k.href=h}catch(q){k=void 0;break b}k=k.protocol;k=":"===k||""===k?"https:":k}Kf(c,f,void 0!==k&&-1!==Sf.indexOf(k.toLowerCase())?h:"about:invalid#zClosurez");break;case 3:Kf(c,f,h.toLowerCase());break;case 4:Kf(c,f,h)}}return c};
Vf=function(a,b,c){b=Hf(b,c);b=document.createTreeWalker(b,5,function(k){if(3===k.nodeType)k=1;else if(Jf(k))if(k=If(k),null===k)k=2;else{var l=a.oZ;k="FORM"!==k&&(l.p6.has(k)||l.uR.has(k))?1:2}else k=2;return k},!1);for(var d=b.nextNode(),e=c.createDocumentFragment(),f=e;null!==d;){var h=void 0;if(3===d.nodeType)h=document.createTextNode(d.data);else if(Jf(d))h=Uf(a,d,c);else throw Error("m");f.appendChild(h);if(d=b.firstChild())f=h;else for(;!(d=b.nextSibling())&&(d=b.parentNode());)f=f.parentNode}return e};
_.Nf=function(a,b){var c=document.implementation.createHTMLDocument("");a=Vf(a,b,c);c=c.body;c.appendChild(a);c=(new XMLSerializer).serializeToString(c);c=c.slice(c.indexOf(">")+1,c.lastIndexOf("</"));return _.Rb(c)};Pf={0:1,1:1};Qf={0:.1,1:.1};
var ag,bg,cg,ig,jg,kg,lg,mg,ng,og,pg,qg,rg,sg,tg,ug,vg,wg,xg,yg,zg,Ag,Bg,Cg,Dg,Eg,Fg,Gg,Hg,Ig,Jg,Mg,Ng;cg=void 0;ig=function(a){try{return _.Va.JSON.parse.call(_.Va.JSON,a)}catch(b){return!1}};jg=function(a){return Object.prototype.toString.call(a)};kg=jg(0);lg=jg(new Date(0));mg=jg(!0);ng=jg("");og=jg({});pg=jg([]);
qg=function(a,b){if(b)for(var c=0,d=b.length;c<d;++c)if(a===b[c])throw new TypeError("Converting circular structure to JSON");d=typeof a;if("undefined"!==d){c=Array.prototype.slice.call(b||[],0);c[c.length]=a;b=[];var e=jg(a);if(null!=a&&"function"===typeof a.toJSON&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(e!==pg||a.constructor!==Array&&a.constructor!==Object)&&(e!==og||a.constructor!==Array&&a.constructor!==Object)&&e!==ng&&e!==kg&&e!==mg&&e!==lg))return qg(a.toJSON.call(a),c);if(null==
a)b[b.length]="null";else if(e===kg)a=Number(a),isNaN(a)||isNaN(a-a)?a="null":-0===a&&0>1/a&&(a="-0"),b[b.length]=String(a);else if(e===mg)b[b.length]=String(!!Number(a));else{if(e===lg)return qg(a.toISOString.call(a),c);if(e===pg&&jg(a.length)===kg){b[b.length]="[";var f=0;for(d=Number(a.length)>>0;f<d;++f)f&&(b[b.length]=","),b[b.length]=qg(a[f],c)||"null";b[b.length]="]"}else if(e==ng&&jg(a.length)===kg){b[b.length]='"';f=0;for(c=Number(a.length)>>0;f<c;++f)d=String.prototype.charAt.call(a,f),
e=String.prototype.charCodeAt.call(a,f),b[b.length]="\b"===d?"\\b":"\f"===d?"\\f":"\n"===d?"\\n":"\r"===d?"\\r":"\t"===d?"\\t":"\\"===d||'"'===d?"\\"+d:31>=e?"\\u"+(e+65536).toString(16).substr(1):32<=e&&65535>=e?d:"\ufffd";b[b.length]='"'}else if("object"===d){b[b.length]="{";d=0;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(e=qg(a[f],c),void 0!==e&&(d++&&(b[b.length]=","),b[b.length]=qg(f),b[b.length]=":",b[b.length]=e));b[b.length]="}"}else return}return b.join("")}};rg=/[\0-\x07\x0b\x0e-\x1f]/;
sg=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;tg=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;ug=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;vg=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;wg=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;xg=/[ \t\n\r]+/g;yg=/[^"]:/;zg=/""/g;Ag=/true|false|null/g;Bg=/00/;Cg=/[\{]([^0\}]|0[^:])/;Dg=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;Eg=/[^\[,:][\[\{]/;Fg=/^(\{|\}|\[|\]|,|:|0)+/;Gg=/\u2028/g;
Hg=/\u2029/g;
Ig=function(a){a=String(a);if(rg.test(a)||sg.test(a)||tg.test(a)||ug.test(a))return!1;var b=a.replace(vg,'""');b=b.replace(wg,"0");b=b.replace(xg,"");if(yg.test(b))return!1;b=b.replace(zg,"0");b=b.replace(Ag,"0");if(Bg.test(b)||Cg.test(b)||Dg.test(b)||Eg.test(b)||!b||(b=b.replace(Fg,"")))return!1;a=a.replace(Gg,"\\u2028").replace(Hg,"\\u2029");b=void 0;try{b=cg?[ig(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(c){return!1}return b&&1===
b.length?b[0]:!1};Jg=function(){var a=((_.Va.document||{}).scripts||[]).length;if((void 0===ag||void 0===cg||bg!==a)&&-1!==bg){ag=cg=!1;bg=-1;try{try{cg=!!_.Va.JSON&&'{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'===_.Va.JSON.stringify.call(_.Va.JSON,{a:[3,!0,new Date(0)],c:function(){}})&&!0===ig("true")&&3===ig('[{"a":3}]')[0].a}catch(b){}ag=cg&&!ig("[00]")&&!ig('"\u0007"')&&!ig('"\\0"')&&!ig('"\\v"')}finally{bg=a}}};_.Kg=function(a){if(-1===bg)return!1;Jg();return(ag?ig:Ig)(a)};
_.Lg=function(a){if(-1!==bg)return Jg(),cg?_.Va.JSON.stringify.call(_.Va.JSON,a):qg(a)};Mg=!Date.prototype.toISOString||"function"!==typeof Date.prototype.toISOString||"1970-01-01T00:00:00.000Z"!==(new Date(0)).toISOString();
Ng=function(){var a=Date.prototype.getUTCFullYear.call(this);return[0>a?"-"+String(1E6-a).substr(1):9999>=a?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1),
"Z"].join("")};Date.prototype.toISOString=Mg?Ng:Date.prototype.toISOString;
var Og=function(){this.Wg=window.console};Og.prototype.log=function(a){this.Wg&&this.Wg.log&&this.Wg.log(a)};Og.prototype.error=function(a){this.Wg&&(this.Wg.error?this.Wg.error(a):this.Wg.log&&this.Wg.log(a))};Og.prototype.warn=function(a){this.Wg&&(this.Wg.warn?this.Wg.warn(a):this.Wg.log&&this.Wg.log(a))};Og.prototype.debug=function(){};_.Pg=new Og;
_.Ch=function(a){if(!a)return"";if(/^about:(?:blank|srcdoc)$/.test(a))return window.origin||"";0===a.indexOf("blob:")&&(a=a.substring(5));a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));c=a.substring(0,a.indexOf("://"));if(!c)throw Error("B`"+a);if("http"!==c&&"https"!==c&&"chrome-extension"!==c&&"moz-extension"!==
c&&"file"!==c&&"android-app"!==c&&"chrome-search"!==c&&"chrome-untrusted"!==c&&"chrome"!==c&&"app"!==c&&"devtools"!==c)throw Error("C`"+c);a="";var d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1);b=b.substring(0,d);if("http"===c&&"80"!==e||"https"===c&&"443"!==e)a=":"+e}return c+"://"+b+a};
_.Qi=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};_.Ri=function(a){var b=_.Qi();if(!a)return b;a=a.split("/");for(var c=0,d=a.length;b&&"object"===typeof b&&c<d;++c)b=b[a[c]];return c===a.length&&void 0!==b?b:void 0};
var El=function(){this.ux={PY:xl?"../"+xl:null,bz:yl,NT:zl,Gra:Al,Jo:Bl,ysa:Cl};this.qg=_.ef;this.iY=this.D7;this.t8=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.ux.PY){this.qg=this.ux.NT(this.qg,this.ux.PY);var a=this.qg.document,b=a.createElement("script");b.setAttribute("type","text/javascript");b.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(b);this.iY=this.qg.doPostMsg}this.bN={};this.FN={};a=(0,_.z)(this.FH,
this);_.tf(this.qg,"message",a);_.jf(_.uf,"RPMQ",[]).push(a);this.qg!=this.qg.parent&&Dl(this,this.qg.parent,this.XI(this.qg.name),"*")};El.prototype.XI=function(a){return'{"h":"'+escape(a)+'"}'};var Jl=function(a){var b=null;0===a.indexOf('{"h":"')&&a.indexOf('"}')===a.length-2&&(b=unescape(a.substring(6,a.length-2)));return b},Kl=function(a){if(!/^\s*{/.test(a))return!1;a=_.Kg(a);return null!==a&&"object"===typeof a&&!!a.g};
El.prototype.FH=function(a){var b=String(a.data);_.Pg.debug("gapix.rpc.receive("+Al+"): "+(!b||512>=b.length?b:b.substr(0,512)+"... ("+b.length+" bytes)"));var c=0!==b.indexOf("!_");c||(b=b.substring(2));var d=Kl(b);if(!c&&!d){if(!d&&(c=Jl(b))){if(this.bN[c])this.bN[c]();else this.FN[c]=1;return}var e=a.origin,f=this.ux.bz;this.t8?_.ef.setTimeout(function(){f(b,e)},0):f(b,e)}};El.prototype.Nb=function(a,b){".."===a||this.FN[a]?(b(),delete this.FN[a]):this.bN[a]=b};
var Dl=function(a,b,c,d){var e=Kl(c)?"":"!_";_.Pg.debug("gapix.rpc.send("+Al+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));a.iY(b,e+c,d)};El.prototype.D7=function(a,b,c){a.postMessage(b,c)};El.prototype.send=function(a,b,c){(a=this.ux.NT(this.qg,a))&&!a.closed&&Dl(this,a,b,c)};var Ll,Ml,Nl,Ol,Pl,Ql,Rl,xl,Al,Sl,Tl,Ul,zl,Bl,Wl,Xl,bm,cm,em,Cl,gm,fm,Yl,Zl,hm,yl,im,jm;Ll=0;Ml=[];Nl={};Ol={};Pl=_.ef.location.href;Ql=_.of(Pl,"rpctoken");Rl=_.of(Pl,"parent")||_.ff.referrer;xl=_.of(Pl,"rly");Al=xl||(_.ef!==_.ef.top||_.ef.opener)&&_.ef.name||"..";Sl=null;Tl={};Ul=function(){};_.Vl={send:Ul,Nb:Ul,XI:Ul};
zl=function(a,b){var c=a;"/"==b.charAt(0)&&(b=b.substring(1),c=_.ef.top);if(0===b.length)return c;for(b=b.split("/");b.length;)if(a=b.shift(),"{"==a.charAt(0)&&"}"==a.charAt(a.length-1)&&(a=a.substring(1,a.length-1)),".."===a)c=c==c.parent?c.opener:c.parent;else if(".."!==a&&c.frames[a]){var d=c.frames[a];if("postMessage"in d)c=d;else if(d instanceof HTMLIFrameElement&&"contentWindow"in d&&"postMessage"in d.contentWindow)c=d.contentWindow;else{var e=null;c=_.ra(c.document.getElementsByTagName("iframe"));
for(var f=c.next();!f.done;f=c.next())if(f=f.value,f.getAttribute("id")==a||f.getAttribute("name")==a)e=f;if(e&&"contentWindow"in e)c=e.contentWindow;else throw Error("O`"+d+"`"+a);}}else return null;return c};Bl=function(a){return(a=Nl[a])&&a.token};Wl=function(a){if(a.f in{})return!1;var b=a.t,c=Nl[a.r];a=a.origin;return c&&(c.token===b||!c.token&&!b)&&(a===c.origin||"*"===c.origin)};
Xl=function(a){var b=a.id.split("/"),c=b[b.length-1],d=a.origin;return function(e){var f=e.origin;return e.f==c&&(d==f||"*"==d)}};_.$l=function(a,b,c){a=Yl(a);Ol[a.name]={ii:b,Iv:a.Iv,it:c||Wl};Zl()};_.am=function(a){delete Ol[Yl(a).name]};bm={};cm=function(a,b){(a=bm["_"+a])&&a[1](this)&&a[0].call(this,b)};em=function(a){var b=a.c;if(!b)return Ul;var c=a.r,d=a.g?"legacy__":"";return function(){var e=[].slice.call(arguments,0);e.unshift(c,d+"__cb",null,b);_.dm.apply(null,e)}};Cl=function(a){Sl=a};
gm=function(a){Tl[a]||(Tl[a]=_.ef.setTimeout(function(){Tl[a]=!1;fm(a)},0))};fm=function(a){var b=Nl[a];if(b&&b.ready){var c=b.mK;for(b.mK=[];c.length;)_.Vl.send(a,_.Lg(c.shift()),b.origin)}};Yl=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),Iv:!0}:{name:a,Iv:!1}};
Zl=function(){for(var a=_.Ri("rpc/residenceSec")||60,b=(new Date).getTime()/1E3,c,d=0;c=Ml[d];++d){var e=c.Lp;if(!e||0<a&&b-c.timestamp>a)Ml.splice(d,1),--d;else{var f=e.s,h=Ol[f]||Ol["*"];if(h)if(Ml.splice(d,1),--d,e.origin=c.origin,c=em(e),e.callback=c,h.it(e)){if("__cb"!==f&&!!h.Iv!=!!e.g)break;e=h.ii.apply(e,e.a);void 0!==e&&c(e)}else _.Pg.debug("gapix.rpc.rejected("+Al+"): "+f)}}};hm=function(a,b,c){Ml.push({Lp:a,origin:b,timestamp:(new Date).getTime()/1E3});c||Zl()};
yl=function(a,b){a=_.Kg(a);hm(a,b,!1)};im=function(a){for(;a.length;)hm(a.shift(),this.origin,!0);Zl()};jm=function(a){var b=!1;a=a.split("|");var c=a[0];0<=c.indexOf("/")&&(b=!0);return{id:c,origin:a[1]||"*",tI:b}};
_.km=function(a,b,c,d){var e=jm(a);d&&(_.ef.frames[e.id]=_.ef.frames[e.id]||d);a=e.id;if(!Nl.hasOwnProperty(a)){c=c||null;d=e.origin;if(".."===a)d=_.Ch(Rl),c=c||Ql;else if(!e.tI){var f=_.ff.getElementById(a);f&&(f=f.src,d=_.Ch(f),c=c||_.of(f,"rpctoken"))}"*"===e.origin&&d||(d=e.origin);Nl[a]={token:c,mK:[],origin:d,Mea:b,IY:function(){var h=a;Nl[h].ready=1;fm(h)}};_.Vl.Nb(a,Nl[a].IY)}return Nl[a].IY};
_.dm=function(a,b,c,d){a=a||"..";_.km(a);a=a.split("|",1)[0];var e=b,f=a,h=[].slice.call(arguments,3),k=c,l=Al,m=Ql,n=Nl[f],p=l,q=jm(f);if(n&&".."!==f){if(q.tI){if(!(m=Nl[f].Mea)){m=Sl?Sl.substring(1).split("/"):[Al];p=m.length-1;for(f=_.ef.parent;f!==_.ef.top;){var u=f.parent;if(!p--){for(var v=null,t=u.frames.length,w=0;w<t;++w)u.frames[w]==f&&(v=w);m.unshift("{"+v+"}")}f=u}m="/"+m.join("/")}p=m}else p=l="..";m=n.token}k&&q?(n=Wl,q.tI&&(n=Xl(q)),bm["_"+ ++Ll]=[k,n],k=Ll):k=null;h={s:e,f:l,r:p,t:m,
c:k,a:h};e=Yl(e);h.s=e.name;h.g=e.Iv;Nl[a].mK.push(h);gm(a)};if("function"===typeof _.ef.postMessage||"object"===typeof _.ef.postMessage)_.Vl=new El,_.$l("__cb",cm,function(){return!0}),_.$l("_processBatch",im,function(){return!0}),_.km("..");
_.r("gapi.rpc.setup",_.km);_.r("gapi.rpc.register",_.$l);_.r("gapi.rpc.call",_.dm);_.r("gapi.rpc.unregister",_.am);_.r("gapi.rpc.sendHandshake",function(a,b){_.km(a)();_.Vl.send(a,_.Vl.XI(b),"*")});
});
// Google Inc.
